### ISSUE TITLE
Missing information in some challenges

### ISSUE THREAD

**Issue by StrixSC** [chainflag/ctf-blockchain-challenges#18]
Hello, I hope you are all well.
Could anyone please tell me what the URL is for the private network used for some of the challenges? 
Also, if possible, update the challenges that are missing some information, such as EasySandbox. I wish I could update it myself, but I am unsure where to obtain the info ! Thanks!

**Comment by iczc** [comment]
Thanks, so do you.
We need to specify the [deployed_addr](https://github.com/chainflag/eth-challenge-base/blob/main/example/challenge.yml#L19) and [web3 provider](https://github.com/chainflag/eth-challenge-base/blob/main/example/.env#L1) only when all players will be using the same pre-deployed contract, otherwise we are allowed specify any web provider as the contract challenge environment. So there is no information missing here.

**Comment by iczc** [comment]
For challenges on [ChainFlag](https://chainflag.org/), it will be deployed on Ropsten testnet if not specified.
